CREATE TYPE "orders_status_enum" AS ENUM (
  'pending',
  'completed',
  'cancelled'
);

CREATE TYPE "payments_status_enum" AS ENUM (
  'pending',
  'completed',
  'failed',
  'refunded'
);

CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" "VARCHAR(100)" NOT NULL,
  "email" "VARCHAR(150)" UNIQUE NOT NULL,
  "phone" "VARCHAR(20)",
  "created_at" TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(200)" NOT NULL,
  "platform" "VARCHAR(50)" NOT NULL,
  "genre" "VARCHAR(50)" NOT NULL,
  "price" "DECIMAL(10,2)" NOT NULL,
  "stock" INT NOT NULL DEFAULT 0,
  "release_Year" "YEAR",
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" INT NOT NULL,
  "total_amount" "DECIMAL(10,2)" NOT NULL DEFAULT 0,
  "status" orders_status_enum DEFAULT 'pending',
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "updated_at" TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" INT NOT NULL,
  "product_id" INT NOT NULL,
  "quantity" INT NOT NULL DEFAULT 1,
  "unit_price" "DECIMAL(10,2)" NOT NULL
);

CREATE TABLE "payments" (
  "id" SERIAL PRIMARY KEY,
  "order_id" INT NOT NULL,
  "amount" "DECIMAL(10,2)" NOT NULL,
  "method" "VARCHAR(50)" NOT NULL,
  "status" payments_status_enum DEFAULT 'pending',
  "paid_at" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT (NOW())
);

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
